version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    volumes:
      - .:/code
      - poetry:/home/docker/.cache
      - .docker/volumes/.bash_aliases:/home/docker/.bash_aliases
    depends_on:
      - database

  database:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

volumes:
  poetry:
  db:
