# Generated by Django 4.1.4 on 2023-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectpagetag_projectpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='short_description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
