version: "3.8"

networks:
  database:
    name: postgresql_database-network
    external: true

services:
  website:
    image: gitea.home.rileymathews.com/rileymathews/personal-site:beta
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal-site.rule=Host(`rileymathews.com`)
      - traefik.http.routers.personal-site.tls.certresolver=le
    networks:
      - database
    restart: unless-stopped
