version: "3.8"

networks:
  database:
    name: postgresql_database-network
    external: true

services:
  website:
    image: gitea.rileymathews.com/rileymathews/personal-site:${SERVICE_TAG}
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal-site.rule=Host(`rileymathews.com`)
      - traefik.http.routers.personal-site.tls.certresolver=le
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URL=$DATABASE_URL
    networks:
      - database
    restart: unless-stopped
